# Generated by Django 6.0.6 on 2026-06-22 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_size', models.PositiveIntegerField(choices=[(16, '16강'), (32, '32강'), (64, '64강')])),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='IN_PROGRESS', max_length=20)),
                ('current_round', models.PositiveIntegerField()),
                ('share_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField()),
                ('match_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_matches', to='items.item')),
                ('right_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_matches', to='items.item')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('winner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_matches', to='items.item')),
            ],
        ),
    ]
